CREATE SCHEMA EC2_SI1N;

USE EC2_SI1N;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
ID_PASS INT PRIMARY KEY,
CPF_PASS VARCHAR(14) NOT NULL,
NOME_PASS VARCHAR(50) NOT NULL,
TEL_PASS VARCHAR(15) NOT NULL,
END_PASS VARCHAR(100) NOT NULL,
EMAIL_PASS VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
ID_AEROPORTO INT PRIMARY KEY,
NOME_AEROPORTO VARCHAR(50) NOT NULL,
LOCAL_AEROPORTO VARCHAR(50) NOT NULL,
PAIS_AEROPORTO VARCHAR(50) NOT NULL,
LONGITUDE_AEROPORTO DECIMAL(9,6) NOT NULL,
LATITUDE_AEROPORTO DECIMAL(9,6) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNC INT PRIMARY KEY,
NOME_FUNC VARCHAR(50) NOT NULL,
FUNCAO_FUNC VARCHAR(50) NOT NULL,
DATA_NASC_FUNC DATE NOT NULL,
TEL_FUNC VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES(
PREFIXO_AERONAVE INT PRIMARY KEY,
MODELO_AERONAVE VARCHAR(50) NOT NULL,
ANO_FAB_AERONAVE DATE NOT NULL,
CAPACIDADE_AERONAVE INT NOT NULL,
FABRICANTE_AERONAVE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
ID_VOO INT PRIMARY KEY,
DATA_HORA_ORIGEM DATETIME NOT NULL,
DATA_HORA_DESTINO DATETIME NOT NULL,
AEROPORTO_ORIGEM INT,
AEROPORTO_DESTINO INT,
ID_AERONAVE INT,
CONSTRAINT ORIGEM_VOO FOREIGN KEY(AEROPORTO_ORIGEM) REFERENCES AEROPORTOS(ID_AEROPORTO),
CONSTRAINT DESTINO_VOO FOREIGN KEY(AEROPORTO_DESTINO) REFERENCES AEROPORTOS(ID_AEROPORTO),
CONSTRAINT AERONAVE_VOO FOREIGN KEY(ID_AERONAVE) REFERENCES AERONAVES(PREFIXO_AERONAVE)
);

CREATE TABLE IF NOT EXISTS RESERVAS(
ID_PASS INT,
ID_VOO INT,
PRIMARY KEY(ID_PASS, ID_VOO),
CONSTRAINT RESERVA_PASS FOREIGN KEY(ID_PASS) REFERENCES PASSAGEIROS(ID_PASS),
CONSTRAINT RESERVA_VOO FOREIGN KEY(ID_VOO) REFERENCES VOOS(ID_VOO)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
ID_FUNC INT,
ID_VOO INT,
PRIMARY KEY(ID_FUNC, ID_VOO),
CONSTRAINT EQUIPES_FUNC FOREIGN KEY(ID_FUNC) REFERENCES FUNCIONARIOS(ID_FUNC),
CONSTRAINT EQUIPES_VOO FOREIGN KEY(iD_VOO) REFERENCES VOOS(ID_VOO)
);

#Adicionando uma coluna para armazenar a nacionalidade dos passageiros
ALTER TABLE PASSAGEIROS
ADD NACIONALIDADE_PASS VARCHAR(50);

#Removendo a coluna END_PASS da tabela PASSAGEIROS
ALTER TABLE PASSAGEIROS
DROP COLUMN END_PASS;

#Modificando o tipo de dados da coluna TEL_PASS para VARCHAR(20)
ALTER TABLE PASSAGEIROS
MODIFY COLUMN TEL_PASS VARCHAR(20);

#Renomeando a coluna FABRICANTE_AERONAVE para MARCA_AERONAVE
ALTER TABLE AERONAVES
CHANGE COLUMN FABRICANTE_AERONAVE MARCA_AERONAVE VARCHAR(50);

#Adicionando um índice na coluna NOME_AEROPORTO para melhorar a busca
ALTER TABLE AEROPORTOS
ADD INDEX IDX_NOME_AEROPORTO (NOME_AEROPORTO);

#Comando DROP para remover a tabela EQUIPES
DROP TABLE EQUIPES;
