CREATE SCHEMA EC5_SI1N;

USE EC5_SI1N;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(100) NOT NULL,
CPF_CLIENTE VARCHAR(20) NOT NULL,
TELEFONE_CLIENTE VARCHAR(13) NOT NULL,
DATANASC_CLIENTE VARCHAR(10) NOT NULL,
STATUSFIDELIDADE_CLIENTE VARCHAR(100) NOT NULL,
CEP_CLIENTE VARCHAR(50) NOT NULL,
RUA_CLIENTE VARCHAR(50) NOT NULL,
NUMCASA_CLIENTE VARCHAR(5) NOT NULL,
BAIRRO_CLIENTE VARCHAR(40) NOT NULL,
IDADE_CLIENTE VARCHAR(3) NOT NULL,
UF_CLIENTE CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PRODUTO INT PRIMARY KEY,
CATEGORIA_PRODUTO VARCHAR(45) NOT NULL,
QUANTIDADEESTOQUE_PRODUTO VARCHAR(20) NOT NULL,
PREÇO_PRODUTO VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(100) NOT NULL,
TELEFONE_FORNECEDOR VARCHAR(13) NOT NULL,
CPF_FORNECEDOR VARCHAR(20) NOT NULL,
EMAIL_FORNECEDOR VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS(
ID_VENDA INT PRIMARY KEY,
VALOR_VENDA VARCHAR(45) NOT NULL,
ID_CLIENTE INT,
CONSTRAINT VENDAS_CLIENTES FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
FORMA_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGAMENTO VARCHAR(45) NOT NULL,
STATUS_PAGAMENTO VARCHAR(30) NOT NULL,
ID_VENDA_PAGT INT,
CONSTRAINT PAGT_VENDAS FOREIGN KEY(ID_VENDA_PAGT) REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
ID_PRODUTO INT,
ID_VENDA INT,
PRIMARY KEY(ID_PRODUTO, ID_VENDA),
QNTDPRODUTO_VENDA VARCHAR(30),
CONSTRAINT PRODTVEND_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT PRODTVEND_VENDAS FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
ID_PRODUTO INT,
ID_FORNECEDOR INT,
PRIMARY KEY(ID_PRODUTO, ID_FORNECEDOR),
CONSTRAINT PRDFORN_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT PRDFORN_FORNECEDORES FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

# ALTER ADD: Adiciona uma nova coluna 'EMAIL_CLIENTE' na tabela CLIENTES.
ALTER TABLE CLIENTES 
ADD EMAIL_CLIENTE VARCHAR(100);

# ALTER DROP COLUMN: Remove a coluna 'CPF_FORNECEDOR' da tabela FORNECEDORES.
ALTER TABLE FORNECEDORES 
DROP COLUMN CPF_FORNECEDOR;

# ALTER MODIFY COLUMN: Modifica o tipo de dado da coluna 'PREÇO_PRODUTO' para DECIMAL na tabela PRODUTOS.
ALTER TABLE PRODUTOS 
MODIFY COLUMN PREÇO_PRODUTO DECIMAL(10,2);

# ALTER CHANGE COLUMN: Renomeia a coluna 'VALOR_VENDA' para 'TOTAL_VENDA' na tabela VENDAS.
ALTER TABLE VENDAS 
CHANGE COLUMN VALOR_VENDA TOTAL_VENDA DECIMAL(10,2);

# ALTER ADD INDEX: Adiciona um índice na coluna 'ID_CLIENTE' na tabela VENDAS para melhorar a performance de busca.
ALTER TABLE VENDAS 
ADD INDEX idx_id_cliente (ID_CLIENTE);

# DROP TABLE: Exclui a tabela PAGAMENTOS do banco de dados, caso não seja mais necessária.
DROP TABLE IF EXISTS PAGAMENTOS;
