#FASE 1: CRIAR O BANCO DE DADOS:
CREATE SCHEMA EC4_SI1N;

#FASE 2: SELECIONAR O NOVO ESQUEMA/DATABASE PARA USO:
USE EC4_SI1N;

#FASE 3 CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS:
CREATE TABLE IF NOT EXISTS ALUNOS(
ID_ALUNOS INT PRIMARY KEY auto_increment,
NOME_ALUNO VARCHAR(50) NOT NULL,
CPF_ALUNO VARCHAR(14) NOT NULL,
DATA_NASC_ALUNO DATE,
RUA_ALUNO VARCHAR(45),
BAIRRO_ALUNO VARCHAR(45),
CIDADE_ALUNO VARCHAR(45),
NUM_CASA_ALUNO VARCHAR(10),
UF_ALUNO CHAR(2),
CEP_ALUNO VARCHAR(45),
EMAIL_ALUNO VARCHAR(100),
TEL_ALUNO VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
ID_INSTRUTOR INT PRIMARY KEY AUTO_INCREMENT,
NOME_INSTRUTOR VARCHAR(45) NOT NULL,
CPF_INSTRUTOR VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODALIDADES(
ID_MODALIDADE INT PRIMARY KEY AUTO_INCREMENT,
NOME_MODALIDADE VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGT INT PRIMARY KEY AUTO_INCREMENT,
ID_ALUNO INT NOT NULL,
DATA_PAGT DATE NOT NULL,
VALOR_PAGT DECIMAL(10,2) NOT NULL,
STATUS_PAGT VARCHAR(20),
CONSTRAINT FK_PAGT_ALUNOS FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS(ID_ALUNOS)
);

CREATE TABLE IF NOT EXISTS PLANO_TREINO(
ID_ALUNOS INT,
ID_INSTRUTOR INT,
PRIMARY KEY(ID_ALUNOS,ID_INSTRUTOR),
PROGRESS_ALUNO VARCHAR(45),
CONSTRAINT FK_TREINO_ALUNO FOREIGN KEY(ID_ALUNOS) REFERENCES ALUNOS(ID_ALUNOS),
CONSTRAINT FK_TREINO_INSTRUTOR FOREIGN KEY(ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES(
ID_INSTRUTOR INT,
ID_MODALIDADE INT,
PRIMARY KEY(ID_INSTRUTOR,ID_MODALIDADE),
CONSTRAINT FK_MODINST_MODALIDADES FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
CONSTRAINT FK_MODINST_INSTRUTORES FOREIGN KEY(ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS AULAS(
ID_AULA INT PRIMARY KEY AUTO_INCREMENT,
HORA_AULA VARCHAR(45) NOT NULL,
CAPC_AULA INT NOT NULL,
ID_INSTRUTOR_MOD INT,
ID_MODALIDADE_INST INT,
CONSTRAINT FK_AULAS_INSTRUTOR FOREIGN KEY(ID_INSTRUTOR_MOD) REFERENCES INSTRUTORES_MODALIDADES(ID_INSTRUTOR),
CONSTRAINT FK_AULAS_MODALIDADE FOREIGN KEY(ID_MODALIDADE_INST) REFERENCES INSTRUTORES_MODALIDADES(ID_MODALIDADE)
);

CREATE TABLE IF NOT EXISTS AULAS_ALUNOS(
ID_ALUNO INT,
ID_AULA INT,
ID_MODALIDADE INT,
ID_INSTRUTOR INT,
PRIMARY KEY(ID_ALUNO,ID_AULA,ID_MODALIDADE,ID_INSTRUTOR),
CONSTRAINT FK_AULASALUNOS_ALUNO FOREIGN KEY(ID_ALUNO) REFERENCES ALUNOS(ID_ALUNOS),
CONSTRAINT FK_AULASALUNOS_AULA FOREIGN KEY(ID_AULA) REFERENCES AULAS(ID_AULA),
CONSTRAINT FK_AULASALUNOS_MODALIDADE FOREIGN KEY(ID_MODALIDADE) REFERENCES AULAS(ID_MODALIDADE_INST),
CONSTRAINT FK_AULASALUNOS_INSTRUTOR FOREIGN KEY(ID_INSTRUTOR) REFERENCES AULAS (ID_INSTRUTOR_MOD)
);

# ALTER ADD: adiciona uma coluna chamada 'GENERO_ALUNO' na tabela ALUNOS
ALTER TABLE ALUNOS 
ADD GENERO_ALUNO CHAR(1);

# ALTER DROP COLUMN: remove a coluna 'CEP_ALUNO' da tabela ALUNOS
ALTER TABLE ALUNOS 
DROP COLUMN CEP_ALUNO;

# ALTER MODIFY COLUMN: altera o tipo de dado da coluna 'TEL_ALUNO' de VARCHAR(45) para VARCHAR(20) na tabela ALUNOS
ALTER TABLE ALUNOS 
MODIFY COLUMN TEL_ALUNO VARCHAR(20);

# ALTER CHANGE COLUMN: renomeia a coluna 'RUA_ALUNO' para 'LOGRADOURO_ALUNO' e altera o tipo para VARCHAR(60) na tabela ALUNOS
ALTER TABLE ALUNOS 
CHANGE COLUMN RUA_ALUNO LOGRADOURO_ALUNO VARCHAR(60);

# ALTER ADD INDEX: cria um índice para a coluna 'CPF_ALUNO' na tabela ALUNOS para melhorar a performance de busca
ALTER TABLE ALUNOS 
ADD INDEX idx_cpf_aluno (CPF_ALUNO);

# Comando DROP: exclui a tabela PAGAMENTOS do banco de dados
DROP TABLE IF EXISTS PAGAMENTOS;
