#FASE 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
#MEU PRIMEIRO BANQUINHO
CREATE SCHEMA EC1_SI1N;

#FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
#USANDO MEU BANQUINHO
USE EC1_SI1N;


# FASE 3: CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS

#CRIANDO A TABELINHA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#NOMEDOATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

#CRIANDO A TABELINHA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

#CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

#FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA

#CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

#CRIANDO A TABELA RECEBIMENTOS (VEIO DEPOIS POIS TEM DEPENDÊNCIA DE PEDIDOS)
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)

#CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#CRIANDO A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

#CRIAR A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
FRPR_QTD INT,
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

# ALTER ADD: Adiciona uma nova coluna 'FORNEC_EMAIL' na tabela FORNECEDORES.
ALTER TABLE FORNECEDORES 
ADD FORNEC_EMAIL VARCHAR(100) NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'FILIAL_CAPACIDADE' de TEXT para VARCHAR(100) na tabela FILIAIS.
ALTER TABLE FORNECEDORES 
MODIFY COLUMN FORNEC_EMAIL VARCHAR(150);

# ALTER CHANGE COLUMN: Renomeia a coluna 'PROD_QUANT' para 'PROD_QUANTIDADE' na tabela PRODUTOS.
ALTER TABLE FORNECEDORES 
CHANGE COLUMN FORNEC_EMAIL EMAIL_FORNEC VARCHAR(150);

# ALTER ADD INDEX: Adiciona um índice na coluna 'PED_FORNECEDOR' na tabela PEDIDOS para melhorar a performance de busca.
ALTER TABLE FORNECEDORES 
ADD INDEX IDX_EMAIL_FORNECEDOR (EMAIL_FORNEC);

# ALTER DROP COLUMN: Remove a coluna 'FORNEC_CONTATO' da tabela FORNECEDORES.
ALTER TABLE FORNECEDORES 
DROP COLUMN EMAIL_FORNEC;

# ALTER ADD: Adiciona uma nova coluna 'FILIAL_EMAIL' na tabela FILIAIS.
ALTER TABLE FILIAIS 
ADD FILIAL_EMAIL VARCHAR(100) NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'FILIAL_CAPACIDADE' de TEXT para VARCHAR(100) na tabela FILIAIS.
ALTER TABLE FILIAIS 
MODIFY COLUMN FILIAL_CAPACIDADE VARCHAR(100);

# ALTER CHANGE COLUMN: Renomeia a coluna 'FILIAL_CAPACIDADE' para 'CAPACIDADE_MAXIMA' na tabela FILIAIS.
ALTER TABLE FILIAIS 
CHANGE COLUMN FILIAL_CAPACIDADE CAPACIDADE_MAXIMA VARCHAR(100);

# ALTER ADD INDEX: Adiciona um índice na coluna 'FILIAL_CODPOSTAL' na tabela FILIAIS para melhorar a performance de busca.
ALTER TABLE FILIAIS 
ADD INDEX IDX_FILIAL_CODPOSTAL (FILIAL_CODPOSTAL);

# ALTER DROP COLUMN: Remove a coluna 'FILIAL_EMAIL' da tabela FILIAIS.
ALTER TABLE FILIAIS 
DROP COLUMN FILIAL_EMAIL;


# ALTER ADD: Adiciona uma nova coluna 'PROD_ORIGEM' na tabela PRODUTOS.
ALTER TABLE PRODUTOS 
ADD PROD_ORIGEM VARCHAR(50) NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'PROD_DESCRICAO' de TEXT para VARCHAR(200) na tabela PRODUTOS.
ALTER TABLE PRODUTOS 
MODIFY COLUMN PROD_DESCRICAO VARCHAR(200);

# ALTER CHANGE COLUMN: Renomeia a coluna 'PROD_ESPECTEC' para 'PROD_ESPECIFICACAO' na tabela PRODUTOS.
ALTER TABLE PRODUTOS 
CHANGE COLUMN PROD_ESPECTEC PROD_ESPECIFICACAO TEXT;

# ALTER ADD INDEX: Adiciona um índice na coluna 'PROD_PRECOUNIT' na tabela PRODUTOS para melhorar a performance de busca.
ALTER TABLE PRODUTOS 
ADD INDEX IDX_PROD_PRECOUNIT (PROD_PRECOUNIT);

# ALTER DROP COLUMN: Remove a coluna 'PROD_ORIGEM' da tabela PRODUTOS.
ALTER TABLE PRODUTOS 
DROP COLUMN PROD_ORIGEM;


# ALTER ADD: Adiciona uma nova coluna 'PED_TOTAL' na tabela PEDIDOS.
ALTER TABLE PEDIDOS 
ADD PED_TOTAL DECIMAL(10,2) NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'PED_STATUS' para VARCHAR(20) na tabela PEDIDOS.
ALTER TABLE PEDIDOS 
MODIFY COLUMN PED_STATUS VARCHAR(20);

# ALTER CHANGE COLUMN: Renomeia a coluna 'PED_PREVISAO' para 'PED_DATA_PREVISAO' na tabela PEDIDOS.
ALTER TABLE PEDIDOS 
CHANGE COLUMN PED_PREVISAO PED_DATA_PREVISAO DATE;

# ALTER ADD INDEX: Adiciona um índice na coluna 'PED_DATA' na tabela PEDIDOS para melhorar a performance de busca.
ALTER TABLE PEDIDOS 
ADD INDEX IDX_PED_DATA (PED_DATA);

# ALTER DROP COLUMN: Remove a coluna 'PED_TOTAL' da tabela PEDIDOS.
ALTER TABLE PEDIDOS 
DROP COLUMN PED_TOTAL;

# ALTER ADD: Adiciona uma nova coluna 'RECEB_TEMPO_ENTREGA' na tabela RECEBIMENTOS.
ALTER TABLE RECEBIMENTOS 
ADD RECEB_TEMPO_ENTREGA INT NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'RECEB_CONDICAO' de TEXT para VARCHAR(100) na tabela RECEBIMENTOS.
ALTER TABLE RECEBIMENTOS 
MODIFY COLUMN RECEB_CONDICAO VARCHAR(100);

# ALTER CHANGE COLUMN: Renomeia a coluna 'RECEB_QUANT_PROD' para 'RECEB_QUANTIDADE' na tabela RECEBIMENTOS.
ALTER TABLE RECEBIMENTOS 
CHANGE COLUMN RECEB_QUANT_PROD RECEB_QUANTIDADE DECIMAL(10,3);

# ALTER ADD INDEX: Adiciona um índice na coluna 'RECEB_DATA' na tabela RECEBIMENTOS para melhorar a performance de busca.
ALTER TABLE RECEBIMENTOS 
ADD INDEX IDX_RECEB_DATA (RECEB_DATA);

# ALTER DROP COLUMN: Remove a coluna 'RECEB_TEMPO_ENTREGA' da tabela RECEBIMENTOS.
ALTER TABLE RECEBIMENTOS 
DROP COLUMN RECEB_TEMPO_ENTREGA;


# ALTER ADD: Adiciona uma nova coluna 'PDPR_DESCONTO' na tabela PEDIDOS_PRODUTOS.
ALTER TABLE PEDIDOS_PRODUTOS 
ADD PDPR_DESCONTO DECIMAL(5,2);

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'PDPR_QUANT' de DECIMAL(10,3) para DECIMAL(12,3) na tabela PEDIDOS_PRODUTOS.
ALTER TABLE PEDIDOS_PRODUTOS 
MODIFY COLUMN PDPR_QUANT DECIMAL(12,3);

# ALTER CHANGE COLUMN: Renomeia a coluna 'PDPR_QUANT' para 'PDPR_QUANTIDADE' na tabela PEDIDOS_PRODUTOS.
ALTER TABLE PEDIDOS_PRODUTOS 
CHANGE COLUMN PDPR_QUANT PDPR_QUANTIDADE DECIMAL(12,3);

# ALTER ADD INDEX: Adiciona um índice na coluna 'PDPR_PEDIDOS' na tabela PEDIDOS_PRODUTOS para melhorar a performance de busca.
ALTER TABLE PEDIDOS_PRODUTOS 
ADD INDEX IDX_PDPR_PEDIDOS (PDPR_PEDIDOS);

# ALTER DROP COLUMN: Remove a coluna 'PDPR_DESCONTO' da tabela PEDIDOS_PRODUTOS.
ALTER TABLE PEDIDOS_PRODUTOS 
DROP COLUMN PDPR_DESCONTO;


# ALTER ADD: Adiciona uma nova coluna 'FLPR_ESTOQUE_MAX' na tabela FILIAIS_PRODUTOS.
ALTER TABLE FILIAIS_PRODUTOS 
ADD FLPR_ESTOQUE_MAX INT NOT NULL;

# ALTER MODIFY COLUMN: Altera o tipo de dado da coluna 'FLPR_QUANT' de DECIMAL(10,3) para DECIMAL(12,3) na tabela FILIAIS_PRODUTOS.
ALTER TABLE FILIAIS_PRODUTOS 
MODIFY COLUMN FLPR_QUANT DECIMAL(12,3);

# ALTER CHANGE COLUMN: Renomeia a coluna 'FLPR_QUANT' para 'FLPR_QUANTIDADE' na tabela FILIAIS_PRODUTOS.
ALTER TABLE FILIAIS_PRODUTOS 
CHANGE COLUMN FLPR_QUANT FLPR_QUANTIDADE DECIMAL(12,3);

# ALTER ADD INDEX: Adiciona um índice na coluna 'FLPR_FILIAL' na tabela FILIAIS_PRODUTOS para melhorar a performance de busca.
ALTER TABLE FILIAIS_PRODUTOS 
ADD INDEX IDX_FLPR_FILIAL (FLPR_FILIAL);

# ALTER DROP COLUMN: Remove a coluna 'FLPR_ESTOQUE_MAX' da tabela FILIAIS_PRODUTOS.
ALTER TABLE FILIAIS_PRODUTOS 
DROP COLUMN FLPR_ESTOQUE_MAX;

# ALTER ADD: Adiciona uma nova coluna 'FRPR_VALIDADE' na tabela FORNECEDORES_PRODUTOS.
ALTER TABLE FORNECEDORES_PRODUTOS 
ADD FRPR_VALIDADE DATE;

# ALTER ADD INDEX: Adiciona um índice na coluna 'FRPR_PRODUTOS' na tabela FORNECEDORES_PRODUTOS para melhorar a performance de busca.
ALTER TABLE FORNECEDORES_PRODUTOS 
ADD INDEX IDX_FRPR_PRODUTOS (FRPR_PRODUTOS);

# ALTER DROP COLUMN: Remove a coluna 'FRPR_VALIDADE' da tabela FORNECEDORES_PRODUTOS.
ALTER TABLE FORNECEDORES_PRODUTOS 
DROP COLUMN FRPR_VALIDADE;

DROP TABLE IF EXISTS FORNECEDORES_PRODUTOS;

DROP TABLE IF EXISTS FILIAIS_PRODUTOS;

DROP TABLE IF EXISTS PEDIDOS_PRODUTOS;

DROP TABLE IF EXISTS RECEBIMENTOS;

DROP TABLE IF EXISTS PEDIDOS;

DROP TABLE IF EXISTS PRODUTOS;

DROP TABLE IF EXISTS FILIAIS;

DROP TABLE IF EXISTS FORNECEDORES;
